anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
cardinal_stake_pool = "GKh7n1S96Kj3jadaqtALZu8i3oMnKkLHDXXKU6fweWX2"
cardinal_reward_distributor = "6566pw1vumw5aw7FKX2iFydBzAF1ubuzPcGxH4vUD5XN"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

[programs.devnet]
cardinal_stake_pool = "GKh7n1S96Kj3jadaqtALZu8i3oMnKkLHDXXKU6fweWX2"
cardinal_reward_distributor = "6566pw1vumw5aw7FKX2iFydBzAF1ubuzPcGxH4vUD5XN"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

[programs.testnet]
cardinal_stake_pool = "GKh7n1S96Kj3jadaqtALZu8i3oMnKkLHDXXKU6fweWX2"
cardinal_reward_distributor = "6566pw1vumw5aw7FKX2iFydBzAF1ubuzPcGxH4vUD5XN"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

[programs.localnet]
cardinal_stake_pool = "GKh7n1S96Kj3jadaqtALZu8i3oMnKkLHDXXKU6fweWX2"
cardinal_reward_distributor = "6566pw1vumw5aw7FKX2iFydBzAF1ubuzPcGxH4vUD5XN"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"
