[scripts]
test = "yarn mocha tests/**/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
cardinal_stake_pool = "J7UH6Lj7JDhRqEgMipbAyjkXWMdUoD5e36EFLJt6Md14"
cardinal_reward_distributor = "CAycEuE9Krg5rPkRDKyWsMPJVJgNFm1tcGPXv8v6foPk"
cardinal_receipt_manager = "GgKDqv8FdwCfgStTnwuYNjifTGJ2wffhNoknn1UJ2sve"