[scripts]
test = "yarn mocha tests/**/*.spec.ts"

[provider]
cluster = "localnet"
# wallet = "./tests/test-key.json"
wallet = "~/.config/solana/id.json"

[programs.mainnet]
cardinal_stake_pool = "B8YPU81FXbC4iicBhbfniTEzeYYXgHnCMsjADJ9agcoy"
cardinal_reward_distributor = "2R6VtKUMcw9G2kwnM2Kimuu1rTMC9DgRgBW8ppUiacGV"
cardinal_group_reward_distributor = "DUJxPunmSUTsMpCPd6wwHZMMySaXiSAiTjwoyQe9ABYQ"
cardinal_receipt_manager = "6pthUZjVSGS3tS4Tz8e826RjqANPzpmpMbW86JcYwH15"

[programs.devnet]
cardinal_stake_pool = "B8YPU81FXbC4iicBhbfniTEzeYYXgHnCMsjADJ9agcoy"
cardinal_reward_distributor = "2R6VtKUMcw9G2kwnM2Kimuu1rTMC9DgRgBW8ppUiacGV"
cardinal_group_reward_distributor = "DUJxPunmSUTsMpCPd6wwHZMMySaXiSAiTjwoyQe9ABYQ"
cardinal_receipt_manager = "6pthUZjVSGS3tS4Tz8e826RjqANPzpmpMbW86JcYwH15"

[programs.testnet]
cardinal_stake_pool = "B8YPU81FXbC4iicBhbfniTEzeYYXgHnCMsjADJ9agcoy"
cardinal_reward_distributor = "2R6VtKUMcw9G2kwnM2Kimuu1rTMC9DgRgBW8ppUiacGV"
cardinal_group_reward_distributor = "DUJxPunmSUTsMpCPd6wwHZMMySaXiSAiTjwoyQe9ABYQ"
cardinal_receipt_manager = "6pthUZjVSGS3tS4Tz8e826RjqANPzpmpMbW86JcYwH15"

[programs.localnet]
cardinal_stake_pool = "B8YPU81FXbC4iicBhbfniTEzeYYXgHnCMsjADJ9agcoy"
cardinal_reward_distributor = "2R6VtKUMcw9G2kwnM2Kimuu1rTMC9DgRgBW8ppUiacGV"
cardinal_group_reward_distributor = "DUJxPunmSUTsMpCPd6wwHZMMySaXiSAiTjwoyQe9ABYQ"
cardinal_receipt_manager = "6pthUZjVSGS3tS4Tz8e826RjqANPzpmpMbW86JcYwH15"
